#pragma once

#define TILES1 "assets/sprites/tiles1.png"
#define TILES2 "assets/sprites/tiles2.png"
#define TILES3 "assets/sprites/tiles3.png"
#define BANNER "assets/sprites/imold4thisbanner.png"
#define MAIN_TILES "assets/sprites/carpet.png"
#define SS_OLDGUY "assets/sprites/spOldGuy.png"
#define FONT1 "assets/fonts/8-bit Arcade In.ttf"
#define ICON "assets/swordIcon.png"
#define BG_MUSIC "assets/audio/oldguy.ogg"
#define CLICK_SFX "assets/audio/click.ogg"
#define STEPS_SFX "assets/audio/stepsfx.ogg"
#define MAZE1 "assets/mazes/maze1.txt"
#define MAZE2 "assets/mazes/maze2.txt"
#define MAZEROOM "assets/mazes/room.txt"